export type EquipmentTypeOption = {
  arabicName: string;
  englishName: string;
  slug: string;
  category: string;
};

const groups: Array<{ category: string; items: Array<[string, string, string]> }> = [
  { category: "معدات الرفع", items: [["كرين 7 طن", "Crane 7 Ton", "crane-7-ton"], ["كرين 10 طن", "Crane 10 Ton", "crane-10-ton"], ["كرين 15 طن", "Crane 15 Ton", "crane-15-ton"], ["كرين 20 طن", "Crane 20 Ton", "crane-20-ton"], ["كرين 25 طن", "Crane 25 Ton", "crane-25-ton"], ["كرين 30 طن", "Crane 30 Ton", "crane-30-ton"], ["كرين 50 طن", "Crane 50 Ton", "crane-50-ton"], ["كرين 70 طن", "Crane 70 Ton", "crane-70-ton"], ["كرين 100 طن", "Crane 100 Ton", "crane-100-ton"], ["كرين 150 طن", "Crane 150 Ton", "crane-150-ton"], ["كرين 200 طن", "Crane 200 Ton", "crane-200-ton"], ["كرين تلسكوبي", "Telescopic Crane", "telescopic-crane"], ["كرين مجنزّر", "Crawler Crane", "crawler-crane"], ["شاحنة كرين", "Truck Crane", "truck-crane"]] },
  { category: "معدات الحفر", items: [["بوكلين صغير", "Mini Excavator", "mini-excavator"], ["بوكلين 120", "Excavator 120", "excavator-120"], ["بوكلين 200", "Excavator 200", "excavator-200"], ["بوكلين 220", "Excavator 220", "excavator-220"], ["بوكلين 300", "Excavator 300", "excavator-300"], ["بوكلين 320", "Excavator 320", "excavator-320"], ["بوكلين 330", "Excavator 330", "excavator-330"], ["بوكلين 350", "Excavator 350", "excavator-350"], ["بوكلين 400", "Excavator 400", "excavator-400"], ["بوكلين 450", "Excavator 450", "excavator-450"], ["بوكلين 500", "Excavator 500", "excavator-500"], ["حفار جنزير", "Crawler Excavator", "crawler-excavator"], ["حفار كفرات", "Wheeled Excavator", "wheeled-excavator"], ["حفار مع بريكر", "Excavator With Breaker", "excavator-with-breaker"]] },
  { category: "معدات التحميل", items: [["شيول صغير", "Small Wheel Loader", "small-wheel-loader"], ["شيول 950", "Wheel Loader 950", "wheel-loader-950"], ["شيول 966", "Wheel Loader 966", "wheel-loader-966"], ["شيول 980", "Wheel Loader 980", "wheel-loader-980"], ["شيول 988", "Wheel Loader 988", "wheel-loader-988"], ["بوبكات S130", "Bobcat S130", "bobcat-s130"], ["بوبكات S450", "Bobcat S450", "bobcat-s450"], ["بوبكات S570", "Bobcat S570", "bobcat-s570"], ["بوبكات S650", "Bobcat S650", "bobcat-s650"], ["بوبكات S770", "Bobcat S770", "bobcat-s770"], ["بوبكات جنزير", "Tracked Skid Steer", "tracked-skid-steer"], ["بوبكات مع مكنسة", "Skid Steer With Sweeper", "skid-steer-with-sweeper"], ["بوبكات مع بريكر", "Skid Steer With Breaker", "skid-steer-with-breaker"], ["جي سي بي (JCB)", "JCB", "jcb"], ["بلدوزر", "Bulldozer", "bulldozer"], ["جريدر", "Grader", "grader"]] },
  { category: "معدات الرفع الخفيف", items: [["بوم لفت 12 متر", "Boom Lift 12m", "boom-lift-12m"], ["بوم لفت 16 متر", "Boom Lift 16m", "boom-lift-16m"], ["بوم لفت 20 متر", "Boom Lift 20m", "boom-lift-20m"], ["بوم لفت 26 متر", "Boom Lift 26m", "boom-lift-26m"], ["بوم لفت 32 متر", "Boom Lift 32m", "boom-lift-32m"], ["سيزر لفت 8 متر", "Scissor Lift 8m", "scissor-lift-8m"], ["سيزر لفت 10 متر", "Scissor Lift 10m", "scissor-lift-10m"], ["سيزر لفت 12 متر", "Scissor Lift 12m", "scissor-lift-12m"], ["مان لفت ديزل", "Diesel Manlift", "diesel-manlift"], ["مان لفت كهربائي", "Electric Manlift", "electric-manlift"]] },
  { category: "معدات المناولة", items: [["فوركلفت 2 طن", "Forklift 2 Ton", "forklift-2-ton"], ["فوركلفت 3 طن", "Forklift 3 Ton", "forklift-3-ton"], ["فوركلفت 5 طن", "Forklift 5 Ton", "forklift-5-ton"], ["فوركلفت 7 طن", "Forklift 7 Ton", "forklift-7-ton"], ["فوركلفت 10 طن", "Forklift 10 Ton", "forklift-10-ton"], ["فوركلفت 15 طن", "Forklift 15 Ton", "forklift-15-ton"], ["فوركلفت كهربائي", "Electric Forklift", "electric-forklift"], ["فوركلفت ديزل", "Diesel Forklift", "diesel-forklift"]] },
  { category: "معدات النقل", items: [["قلاب 3 متر", "Dump Truck 3m", "dump-truck-3m"], ["قلاب 6 متر", "Dump Truck 6m", "dump-truck-6m"], ["قلاب 8 متر", "Dump Truck 8m", "dump-truck-8m"], ["قلاب 12 متر", "Dump Truck 12m", "dump-truck-12m"], ["قلاب 18 متر", "Dump Truck 18m", "dump-truck-18m"], ["قلاب 24 متر", "Dump Truck 24m", "dump-truck-24m"], ["قلاب صخور", "Rock Dump Truck", "rock-dump-truck"], ["قلاب مخلفات", "Waste Dump Truck", "waste-dump-truck"], ["سطحة نقل معدات", "Equipment Flatbed", "equipment-flatbed"], ["لوبد", "Lowbed", "lowbed"], ["تريلا", "Trailer", "trailer"], ["رأس وتيدر", "Tractor Head And Tipper", "tractor-head-tipper"], ["وايت ماء", "Water Truck", "water-truck"], ["تنكر ماء", "Water Tanker", "water-tanker"], ["تنكر ديزل", "Diesel Tanker", "diesel-tanker"]] },
  { category: "معدات الطاقة والتشغيل", items: [["مولد 30 KVA", "Generator 30 KVA", "generator-30-kva"], ["مولد 60 KVA", "Generator 60 KVA", "generator-60-kva"], ["مولد 100 KVA", "Generator 100 KVA", "generator-100-kva"], ["مولد 250 KVA", "Generator 250 KVA", "generator-250-kva"], ["مولد 500 KVA", "Generator 500 KVA", "generator-500-kva"], ["مولد 1 ميجا", "Generator 1 MW", "generator-1mw"], ["مولد صامت", "Silent Generator", "silent-generator"], ["كمبروسر 185 CFM", "Compressor 185 CFM", "compressor-185-cfm"], ["كمبروسر 375 CFM", "Compressor 375 CFM", "compressor-375-cfm"], ["كمبروسر 750 CFM", "Compressor 750 CFM", "compressor-750-cfm"]] },
  { category: "معدات الطرق", items: [["رصاصة صغيرة", "Small Roller", "small-roller"], ["رصاصة 10 طن", "Roller 10 Ton", "roller-10-ton"], ["رصاصة 12 طن", "Roller 12 Ton", "roller-12-ton"], ["رصاصة 20 طن", "Roller 20 Ton", "roller-20-ton"], ["فرادة أسفلت", "Asphalt Paver", "asphalt-paver"], ["كشاطة أسفلت", "Asphalt Milling Machine", "asphalt-milling-machine"]] }
];

export const equipmentTypeGroups = groups.map((group) => ({
  category: group.category,
  items: group.items.map(([arabicName, englishName, slug]) => ({ arabicName, englishName, slug, category: group.category }))
}));

export const equipmentTypes = equipmentTypeGroups.flatMap((group) => group.items);
